spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(dCrVdmLp5QC4flIjQcqC5LVL0iArF6vwN46lxhIkT+v7r3YbU+oywvSid1Cnu044RDnhn2taVIZZhGm7QisUWXUctrA8rDr/Zmh7N6KZtA1I+TBYdnDNRv1lSvg9xiPL9kFo+kUjAObhGcQKTMs8y4FBlxb3qkjX/yp1stoCnV0EnmhxHjexDXVFy5j3FnAs8g8mw77ReJZTdD3gr6whG0CEQsgYFJROx/bzjkNZ5ONgkdHd9MlbSA==)
    username: ENC(tlS7O0VbZkEPjggphSj3RA==)
    password: ENC(4PBHAwxJhkDv+8tL9aGE+PfYMv0h5ZB2)
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ENC(BMUgJ2G8uwbuCSiZKAzMbzmsJTX1JtoaYsim7q8KVPXlFoztSi1eSkQpprZM6HoJ)
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://49.50.173.88:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
