spring:
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ENC(N7RrOIacldwE0oXmIzILUmmaCTG5BYRfGtbv2T4n7aU/TwEtx9eShK6jDUpiSEQj6kRaI1uKG/r0/4GKZoWWWA==)
  profiles:
    active: local

logging:
  level:
    resumarble.core.domain.gpt.client: DEBUG

springdoc:
  swagger-ui:
    path: /swagger

jasypt:
  encryptor:
    password: resumarble-backend

external:
  openai:
    url: https://api.openai.com
    token: ENC(rAYsw0jbXV5NfG0pKimswwaOldvl93RPcJrQZK/rGNQc5mm3aQrHI6p/LorED98dWNiNmDvWjidQgV2toXFiXA==)
