server:
  tomcat:
    threads:
      max: 200
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000

spring:
  profiles:
    active: local
  mvc:
    async:
      request-timeout: 60000

logging:
  level:
    resumarble.core.domain.gpt.client: DEBUG

springdoc:
  swagger-ui:
    path: /swagger

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

jwt:
  secret-key: ENC(lrBnCZFjSWFI5R8i2I/1kd7ePdWgkXfmI4YNvTAvwiC3xNWgiBZmQwD8pr+1Wlh5ADMew1sWh5piKAp6AmjtNW7gdFgEe6bvdAGwsDeIYodiPNfa6GaMFQ==)
external:
  openai:
    url: https://api.openai.com
    token: ENC(18XqK2igPaqRkgV3mWHhb3w6SMoNJNqdQuGQRmikY3YpkWeV2t+SSmF3RHQCXd0KPsHbeYg/u03eZzB5F5sp9w==)

