DROP TABLE IF EXISTS job;
CREATE TABLE job
(
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    job_title_kr  VARCHAR(255) NOT NULL,
    job_title_en  VARCHAR(255) NOT NULL,
    created_date  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4,
  COLLATE = utf8mb4_bin;

DROP TABLE IF EXISTS prompt;
CREATE TABLE prompt
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    is_deleted  BOOLEAN NOT NULL DEFAULT false,
    prompt_type ENUM('INTERVIEW_QUESTION') NOT NULL,
    content     TEXT NOT NULL COMMENT "내용",
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4,
  COLLATE = utf8mb4_bin;



