server:
  port: 8081

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

external:
  openai:
    url: https://api.openai.com
    token: ENC(18XqK2igPaqRkgV3mWHhb3w6SMoNJNqdQuGQRmikY3YpkWeV2t+SSmF3RHQCXd0KPsHbeYg/u03eZzB5F5sp9w==)
