server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/resumarble_reactor?useSSL=false&serverTimezone=UTC
    username: ENC(tlS7O0VbZkEPjggphSj3RA==)
    password: ENC(2DPtU8Z8QpWHMFjf+AnbfQ==)
    pool:
      enabled: true
      initial-size: 10
      max-acquire-time: 5s
      max-create-connection-time: 5s
      max-idle-time: 60m
      max-life-time: 60m
      max-size: 10

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

external:
  openai:
    url: https://api.openai.com
    token: ENC(18XqK2igPaqRkgV3mWHhb3w6SMoNJNqdQuGQRmikY3YpkWeV2t+SSmF3RHQCXd0KPsHbeYg/u03eZzB5F5sp9w==)
