server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: resumarble-main
          uri: https://www.resumarble.site
          predicates:
            - Path=/**

external:
  jwt:
    secret-key: ENC(lrBnCZFjSWFI5R8i2I/1kd7ePdWgkXfmI4YNvTAvwiC3xNWgiBZmQwD8pr+1Wlh5ADMew1sWh5piKAp6AmjtNW7gdFgEe6bvdAGwsDeIYodiPNfa6GaMFQ==)
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
