server:
  port: 9000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://www.resumarble.site"
              - "https://resumarble.site"
              - "http://localhost:3000"
              - "http://localhost:8080"
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: resumarble-reactor
          uri: http://localhost:8081
          predicates:
            - Path=/interview-questions/**
            - Header=Authorization, Bearer\s+.*
          filters:
            - name: JwtAuthenticationGatewayFilter
              args:
                name: jwtAuthenticationGatewayFilter
        - id: resumarble-user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

external:
  jwt:
    secret-key: ENC(lrBnCZFjSWFI5R8i2I/1kd7ePdWgkXfmI4YNvTAvwiC3xNWgiBZmQwD8pr+1Wlh5ADMew1sWh5piKAp6AmjtNW7gdFgEe6bvdAGwsDeIYodiPNfa6GaMFQ==)
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
