server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: resumarble-reactor
          uri: http://localhost:8081
          predicates:
            - Path=/interview-questions/**
            - Header=
          filters:
            - name: JwtAuthenticationGatewayFilter
              args:
                name: jwtAuthenticationGatewayFilter

external:
  jwt:
    secret-key: ENC(lrBnCZFjSWFI5R8i2I/1kd7ePdWgkXfmI4YNvTAvwiC3xNWgiBZmQwD8pr+1Wlh5ADMew1sWh5piKAp6AmjtNW7gdFgEe6bvdAGwsDeIYodiPNfa6GaMFQ==)
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
